@startuml
interface Creator {
    FactoryMethod()
    AnOperation() // has default implemention
}

class ConcreteCreator {
    FactoryMethod()
}
Creator <|.. ConcreteCreator

interface Product {
}

class ConcreteProduct {
}
Product <|.. ConcreteProduct
ConcreteCreator --> ConcreteProduct
@enduml