@startuml
interface Beverage {
    GetDescription()
    GetCost()
}

class Coffee1 {
    GetDescription()
    GetCost()
}
Beverage <|.. Coffee1

class Coffee2 {
    GetDescription()
    GetCost()
}
Beverage <|.. Coffee2

class DecoratorMilk {
    Beverage b
    GetDescription()
    GetCost()
}
Beverage <|.. DecoratorMilk

class DecoratorSalt {
    Beverage b
    GetDescription()
    GetCost()
}
Beverage <|.. DecoratorSalt

@enduml