@startuml
interface Beverage {
    GetDescription()
    GetCost()
}

class Coffee {
    GetDescription()
    GetCost()
}
Beverage <|.. Coffee

class Decorator {
    Beverage b
    GetDescription()
    GetCost()
}
Beverage <|.. Decorator
@enduml